FROM python:3.11-slim

WORKDIR /app

# Install only what's needed
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy only necessary files
COPY ./services ./services
COPY ./files ./files

ENV PYTHONPATH=.

# Run Celery worker directly
CMD ["celery", "-A", "services.main.celery_app", "worker", "--loglevel=info"]
